title: Ravencoin
author: RavenProject
description: A peer-to-peer blockchain designed to handle the efficient creation and transfer of assets from one party to another. It's an open-source project based on Bitcoin

baseurl: "/ravenproject.github.io"

# social links
twitter_username: ravencoin
github_username:  RavenProject
rss: rss

show_excerpts: false

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# Build settings
theme: minima
relative_permalinks: false

# Reading Files
include:
  - _pages
  - _pages_de
  - _posts
  - _wallets
  - _translations

locales:
  - default:
    baseurl: "/"
    name: English
    lang: en-US
  - de:
    baseurl: /de
    name: Deutsch
    lang: de-De

permalink: pretty

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      lang: en-US
  - scope:
      path: "*_de/"
    values:
      locale: de
      lang: de-De
      permalink: "/de/:basename"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
